### ISSUE TITLE
Option to select the Price as per user role for the orders created manually.

### ISSUE THREAD

**Issue by Shasvat7** [TycheSoftwares/price-by-user-role-for-woocommerce#21]
When we create the order manually from the backend then the prices of the products added are taken as per the admin roles, but if one wants to create the order and take the prices as per the different roles then it is not possible to do that.

So suppose, there is Product A and in that price for Customer is set as 100 and Admin Price is set to 50
now when the admin creates an order manually for his client (who is a customer) he wants the Price of the Product to be 100 and not 50. so there should be an option to select the prices as per user roles for the products added for that order.

Ticket:- https://tychesoftwares.freshdesk.com/a/tickets/26635
https://wordpress.org/support/topic/prices-per-role-for-orders-created-from-back-office/

**Comment by apeksha10** [comment]
Re-opening this issue 

Selected the price as per user role does not appear when I create the order manually.
https://www.screencast.com/t/YIuato306
https://www.screencast.com/t/0xWKpsYplW

**Comment by apeksha10** [comment]
Re-opening this issue 

Still, I am able to replicate the above issue 
Followed all steps as the issue has. 
Discussed with @nidhitatosaniya

**Comment by apeksha10** [comment]
There is some cache issue 
Things worked well
That's why I am closing this issue.
