### ISSUE TITLE
Product Price by User Roles: per product feature is not working and the console shows some error.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/price-by-user-role-for-woocommerce#25]
**Describe the bug**
Product Price by User Roles: per product feature is not working and the console shows some error.

**To Reproduce**
1. Take the latest git copy
2. Enabled Enable per product settings. https://www.screencast.com/t/IjIzB8cHm2P
3. Go to edit product page, try to enabled per product feature.
4. Plugin does not allow me to enabled per product option and console shows some error
 see the video : https://www.screencast.com/t/8toDg0Xtm9

**Expected behavior**
The plugin should allow to enabled Per product settings and the console does not show any error which comes from our plugin.

**Comment by Shasvat7** [comment]
This is not an issue from the plugin, but this issue is coming due to the wrong folder name coming when the plugin copy taken from the github as the Repository name was wrong.
I have changed the repo name so now this issue will not be replicated and hence, I am closing this issue.
